export const robots = [
{   id: 1,
    name: "Tosyn",
    username: 'youngboss',
    email: 'tosyn@robots.com',
},
{   id: 2,
    name: "Basil TJ",
    username: 'apulengee',
    email: 'apu.ng@robots.com',
},
{   id: 3,
    name: "Chibuzor",
    username: 'chibuu',
    email: 'chibu.ozor@robots.com',
},
{   id: 4,
    name: "Uche",
    username: 'uchemoney',
    email: 'eche@robots.com',
},
{   id: 5,
    name: "Me",
    username: 'mebaby',
    email: 'me@robots.com'
},
{   id: 6,
    name: "Victory",
    username: 'kudepaara',
    email: 'kude@robots.com',
},
{   id: 7,
    name: "Francis",
    username: 'lomi',
    email: 'lomi@robots.com',
},
{   id: 8,
    name: "Jebe",
    username: 'Jebelayon',
    email: 'J.Layon@robots.com',
},
{   id: 9,
    name: "Joseph",
    username: 'timon',
    email: 'timon.j@robots.com',
},
{   id: 10,
    name: "Divine",
    username: 'young_evangelist',
    email: 'e.divine@robots.com',
},
]